name: Build and Test 
on: [push]

jobs:
  build:
    runs-on: windows-latest
    env:
      SEMANTIC_VERSION: 1.0.${{github.run_number}}
    strategy:
      matrix:
        dotnet-version: ['5.0.x']

    steps:
      - run: echo "The build number is ${{github.run_number}}."
      - run: echo "The build number is ${{env.SEMANTIC_VERSION}}."
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
        #Set Semantic Verion 
      - run: '((Get-Content -path CA.Blocks.Images.csproj -Raw) -replace "987.654.3210","${{env.SEMANTIC_VERSION}}") | Set-Content -Path CA.Blocks.Images.csproj'
        shell: powershell
        working-directory: ${{github.workspace}}\CA.Blocks.Images\
      - run: '((Get-Content -path CA.Images.csproj -Raw) -replace "987.654.3210","${{env.SEMANTIC_VERSION}}") | Set-Content -Path CA.Images.csproj'
        shell: powershell
        working-directory: ${{github.workspace}}\CA.Images\
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Publish
        run: dotnet publish ${{ github.workspace}}/CA.Images/CA.Images.csproj -c Release -o image_app
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CaImageBuild_${{env.SEMANTIC_VERSION}}
          path: image_app/**
          if-no-files-found: error
          retention-days: 10
  release:
    name: Relase output
    runs-on: windows-latest
    needs: build
    env:
      SEMANTIC_VERSION: 1.0.${{github.run_number}}
    steps:
      - name: Download Content
        uses: actions/download-artifact@v3
        with: 
          name: CaImageBuild_${{env.SEMANTIC_VERSION}}
      - name: archive output
        uses: thedoctor0/zip-release@master
        with:
          filename: release.zip
      - name: Create GitHub Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{github.run_number}}
          release_name: Release v1.0.${{github.run_number}}  
      - name: Upload Output to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: CaImageBuild_${{env.SEMANTIC_VERSION}}.zip
          asset_content_type: application.zip