name: Build and Test 
on: [push]

env:
  CODE_PRODUCT_VERSION: 1.0.

jobs:
  build:
    runs-on: windows-latest
    env:
      SEMANTIC_VERSION: $CODE_PRODUCT_VERSION${{github.run_number}}
    strategy:
      matrix:
        dotnet-version: ['5.0.x']

    steps:
      - run: echo "The CODE_PRODUCT_VERSION is ${{env.CODE_PRODUCT_VERSION}}"
      - run: echo "The build number is ${{github.run_number}}."
      - run: echo "The build number is ${{SEMANTIC_VERSION}}."
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal