name: Build and Test 
on: [push]

env:
  major: ${{1}}
  minor: ${{0}}
  patch: ${{github.run_number}}
  semantic_verion: ${{env.major}}.${{env.minor}}.${{env.patch}}

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x']

    steps:
      - run: echo "The build number is ${{github.run_number}}."
      - run: echo "The build number is ${{env.semantic_verion}}."
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal